### ISSUE TITLE
Exact p-value calculation does not work if there are zeros.

### ISSUE THREAD

**Issue by jarrodmillman** [scipy-lectures/scipy-lecture-notes#619]
We are getting the following warning on `main`:
```
packages/statistics/index.rst::index.rst
  /opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
    warnings.warn("Exact p-value calculation does not work if there are "
```

@mdhaber Thoughts?

**Comment by mdhaber** [comment]
Looks like `wilcoxon`. It didn't happen in CI before?

**Comment by jarrodmillman** [comment]
I think it has been happening (not certain), but I am trying to deal with all the remaining warnings now.  Here is a more complete error message:
```
402 This is equivalent to a one-sample test on the differences between paired
403 observations::
404
405     >>> sp.stats.ttest_1samp(data['FSIQ'] - data['PIQ'], 0) 
406     TtestResult(statistic=1.784201940..., pvalue=0.082172638..., df=39)
407 
408 Accordingly, we can perform a nonparametric version of the test with
409 ``wilcoxon``.
410 
411     >>> sp.stats.wilcoxon(data['FSIQ'], data['PIQ'])
UNEXPECTED EXCEPTION: UserWarning('Exact p-value calculation does not work if there are zeros. Switching to normal approximation.')
Traceback (most recent call last):
  File "/usr/lib64/python3.11/doctest.py", line 1351, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest index.rst[36]>", line 1, in <module>
  File "/home/jarrod/.venv/lectures/lib64/python3.11/site-packages/scipy/_lib/_util.py", line 713, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jarrod/.venv/lectures/lib64/python3.11/site-packages/scipy/stats/_axis_nan_policy.py", line 523, in axis_nan_policy_wrapper
    res = hypotest_fun_out(*samples, **kwds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jarrod/.venv/lectures/lib64/python3.11/site-packages/scipy/stats/_morestats.py", line 4088, in wilcoxon
    warnings.warn("Exact p-value calculation does not work if there are "
UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
/home/jarrod/src/scipy-lecture-notes/packages/statistics/index.rst:411: UnexpectedException
```

Does #623 seem reasonable?

**Comment by mdhaber** [comment]
Yup. Just approved that.
